### ISSUE TITLE
Not work with multiple files

### ISSUE THREAD

**Issue by LeoVS09** [tomasAlabes/stylefmt-loader#10]
Don't format multiple files when they connected with `@import` declaration.
Example:
``` scss
// main.scss
@import './footer.scss'
h2 {
 color:black;
}
```
``` scss
// footer.scss
a {
 color:black;
}
```
`main.scss` will be formate, but `footer.scss` not.
